### ISSUE TITLE
Process Meeting 11-4-15

### ISSUE THREAD

**Issue by tymulholland** [wildland/guides#33]
- [x] Making component repos private
- [x] When to Open Source
- [ ] Applications in their own Organization

**Comment by jweakley** [comment]
Address workflow/patterns/standards. See https://github.com/wildland/distilltech-web/issues/143

**Comment by jweakley** [comment]
Address inline editing vs separate pages. See https://github.com/wildland/distilltech-web/issues/213

**Comment by jweakley** [comment]
How to handle deletes

**Comment by jweakley** [comment]
Large collections, how to display. Pagination?

**Comment by jweakley** [comment]
Selectize not working with tab form element jumping.

**Comment by jweakley** [comment]
Herd

**Comment by jweakley** [comment]
App structure. Menu bar and form type stuff. See https://github.com/wildland/wordland

**Comment by jweakley** [comment]
Trailing commas, yes/no

**Comment by tymulholland** [comment]
Do we need an office beaver, yes/no?

**Comment by Samsinite** [comment]
Have JS devs comment on https://github.com/wildland/denovo/pull/314 to determine what we want our jscs settings to be across all projects (which we own/create and are not inherited).

**Comment by Samsinite** [comment]
What we need to be testing and validating (on both ember/rails) before building on `rake pre_deploy` and abort if failed.
